name: Build vagrant box
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Apt update
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install -y virtualbox vagrant
      # conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
      # - name: Install vagrant plugin vbguest
      #   run: vagrant plugin install vagrant-vbguest
      - name: Provisioning box
        run: vagrant up
